// <auto-generated />
using System;
using Despachantes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Despachantes.Migrations
{
    [DbContext(typeof(DespachanteContext))]
    partial class DespachanteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("Despachantes.Model.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Despachantes.Model.Servico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Valor")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Servicos");
                });

            modelBuilder.Entity("Despachantes.Model.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Ano")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Fk_Cliente")
                        .HasColumnType("int");

                    b.Property<string>("MarcaModelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Placa")
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("Renavam")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.HasKey("Id");

                    b.HasIndex("Fk_Cliente");

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("Despachantes.Models.SituacaoSV", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("Id");

                    b.ToTable("SituacaoSV");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "ATIVO"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "FINALIZADO"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "PENDENTE"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "CANCELADO"
                        });
                });

            modelBuilder.Entity("Despachantes.Models.VeiculoServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataDeEntrada")
                        .HasColumnType("datetime");

                    b.Property<int>("Fk_Servico")
                        .HasColumnType("int");

                    b.Property<int>("Fk_Situacao")
                        .HasColumnType("int");

                    b.Property<int>("Fk_Veiculo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Fk_Servico");

                    b.HasIndex("Fk_Situacao");

                    b.HasIndex("Fk_Veiculo");

                    b.ToTable("VeiculosServicos");
                });

            modelBuilder.Entity("Despachantes.Model.Veiculo", b =>
                {
                    b.HasOne("Despachantes.Model.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("Fk_Cliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Despachantes.Models.VeiculoServico", b =>
                {
                    b.HasOne("Despachantes.Model.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("Fk_Servico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Despachantes.Models.SituacaoSV", "SituacaoSV")
                        .WithMany()
                        .HasForeignKey("Fk_Situacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Despachantes.Model.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("Fk_Veiculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Servico");

                    b.Navigation("SituacaoSV");

                    b.Navigation("Veiculo");
                });
#pragma warning restore 612, 618
        }
    }
}
